sudo: required
addons:
  apt:
    update: true
    packages:
      - docker-ce
services:
  - docker
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - source sha_function.sh
  - flag_alpine=$(is_base "treehouses/alpine:latest" "kaiyfan/novnc:latest")
  - echo $flag_alpine
  - echo $DOCKERAPIKEY | docker login -u "kaiyfan" --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "./docker-build.sh treehouses/alpine:latest arm arm64 amd64"
  - flag=$(compare "treehouses/alpine:latest" "kaiyfan/novnc:latest")
  - echo $flag
before_deploy:
  - tag_time=$(date +%Y%m%d%H%M)
  - echo $tag_time
  - tag_latest="latest"
  - create_manifest kaiyfan/novnc $tag_latest $tag_time kaiyfan/novnc-tags:arm kaiyfan/novnc-tags:arm64 kaiyfan/novnc-tags:amd64 kaiyfan/novnc-tags
  - docker manifest inspect kaiyfan/novnc:$tag_latest
  - docker manifest inspect kaiyfan/novnc:$tag_time
deploy:
  - provider: script
    script: docker manifest push kaiyfan/novnc:$tag_latest; docker manifest push kaiyfan/novnc:$tag_time
    skip_cleanup: true
    on:
      all_branches: true
      condition: "$flag = true"
env:
  global:
    secure: "RNHaL9eFQgk5hd6IaExWfi/L2jHBpvZ5m/4XfMJZb+EdRTZYEZTVyjg41MnNFJPt1D28lvlVKGjsBaP46eS59zCcD9UhcV5+WWlRvZKNFxRJxcLOX/Pic8nHGwBuN8/JzT3vswEusD9NT9uamWpULK1jDFSaNkLR2fb7RuFUWag3dzClyEZowsvlFGeX5lbW/L8Ma3dCM6MNKTRJHEkIprSpmIjDfHs2L7K6DrF0ko+kkKAquhryxxqeQtJBN3+GsMfa1/8Q2NaeHqZ74NegmLTvwnHyO8eC7igLaQpZlMgLUpt5iwluTdCrRdPNfdBAjmJ/ZCQYVyxsQDQZlNjusun2R/b/pBcjursD78RAkyXzVJog2kxAwzxAB5EwASuy9vsgSOOdGqEE/W45MFv7X9hbNC7SwvAOyJJi7KyW1jFAiykxH9i+pBeGsyb6+FemwYrj5FYJi6ESzbuNr0irNPmYKmssCbDSSWe3S+7UFrNwh9SqL8kxr0kzzf9GrHzGea7XXzHXPh6PZ99gziyubAPp0wFkwytdfq8cOMQW+LvmHJGfwsBcdOJf16VRoTDb4wCaTyeWaInOKfl5zUk72W/l1tURzoxAdViaqAboBqA4ECBiSjZMsfp6gBtLXTAjtZwL0n4RuMLEH6avHgoH/B5sTtquQJc5qhJLTS4SXWo="